### ISSUE TITLE
ApiClient.login 에러

### ISSUE THREAD

**Issue by luftaquila** [archethic/node-kakaolink#4]
좋은 모듈 만들어 주셔서 감사합니다.
거의 1년째 이 모듈을 사용해 서비스 잘 운영하고 있었는데, 이번 주부터 갑자기 다음과 같은 에러가 발생합니다.

에러 스택을 따라가 보니 `cheerio` 모듈이 가지고 오는 HTML 구조가 변경된 듯한데, 혹시 수정이 가능할까 하여 이슈로 남겨 봅니다.

감사합니다.
```
TypeError: Cannot read properties of undefined (reading 'toString')
    at ApiClient.login (/home/luftaquila/ajounotice/node_modules/node-kakaolink/dist/api/api-client.js:66:123)
    at Object.kakaoLogin (file:///home/luftaquila/ajounotice/src/login.mjs:49:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async init (file:///home/luftaquila/ajounotice/index.mjs:18:3)
```

**Comment by naijun0403** [comment]
안녕하세요, 현제 해당 모듈은 deprecated 되었으며, 일주일 내로 api를 개선한 모듈을 업로드 할 예정입니다. 죄송합니다

**Comment by luftaquila** [comment]
아닙니다 유용한 모듈 만들어 주셔서 대단히 감사합니다 :D

**Comment by luftaquila** [comment]
https://github.com/naijun0403/kakaolink/ 에 버그 픽스를 올려주신 것은 보았는데 혹시 이 레포지토리는 deprecated된 모듈일까요?

감사합니다.

**Comment by naijun0403** [comment]
> https://github.com/naijun0403/kakaolink/ 에 버그 픽스를 올려주신 것은 보았는데 혹시 이 레포지토리는 deprecated된 모듈일까요?
> 
> 감사합니다.

아직은 아니지만... 곧 리펙터링된 모듈이 올라온다면 이 레포는 deprecated 될 예정입니다. 아마 이번주 내로 올라갈꺼 같네요

**Comment by luftaquila** [comment]
@naijun0403 안녕하세요.. 로그인 통과해서 기능만 작동할 수 있도록 혼자 고쳐보려고 했는데 알아내기가 쉽지 않네요. 혹시 어느 부분을 고쳐야 바뀐 방식에 대응할 수 있을지 언질이라도 해주실 수 있을까요?

https://github.com/naijun0403/kakaolink/ 레포를 사용해 보려고 했는데 네이티브 앱에 로딩되어 사용하는 모듈인지 java.util 모듈을 사용하는 부분이 있어 node.js 환경에서 사용이 불가능하네요.

감사합니다.

**Comment by naijun0403** [comment]
> 안녕하세요.. 로그인 통과해서 기능만 작동할 수 있도록 혼자 고쳐보려고 했는데 알아내기가 쉽지 않네요. 혹시 어느 부분을 고쳐야 바뀐 방식에 대응할 수 있을지 언질이라도 해주실 수 있을까요?

먼저, 레포 수정이 늦어지는거에 대해 죄송합니다. 최근에 너무 바쁜일이 많아 시간이 그리 많지 않았습니다.

request 부분을 제외하고 대부분의 기능을 자바스크립트로 구현하려 노력하여, request-client 부분과 쿠키 관련 기능을 수정하신다면 아마 될겁니다.

**Comment by luftaquila** [comment]
@naijun0403 아닙니다. 제가 자꾸 부탁드려 죄송하네요. 말씀해주신 부분 한 번 확인해 보겠습니다. 늦은 시간까지 고생 많으십니다. 도움 주셔서 감사합니다.
